from typing import Any, Protocol, Sequence


class Cache(Protocol):
    async def get_value(self, key: Any) -> Any: ...
    async def set_value(
        self, key: Any, value: Any, expire: int | None = None, **kw: Any
    ) -> None: ...
    async def del_keys(self, *keys: Any) -> None: ...
    async def get_list(self, key: Any) -> Sequence[Any]: ...
    async def set_list(
        self, key: Any, *values: Any, expire: int | None = None, **kw: Any
    ) -> None: ...
    async def remove_from_list(self, key: Any, value: Any, **kw: Any) -> Any: ...
    async def close(self) -> None: ...
